/-
This file was generated by Aristotle.

Lean Toolchain version: leanprover/lean4:v4.20.0-rc5
Mathlib version: d62eab0cc36ea522904895389c301cf8d844fd69 (May 9, 2025)
-/

/-
We define the notion of quantifier elimination for a first-order theory T in a language L.
A theory T has quantifier elimination if for every L-formula phi, there exists a quantifier-free L-formula psi such that T models phi if and only if T models psi.
This is formalized as `HasQuantifierElimination`
[Mathias]; this was generated using the prompt interface of Aristotle, witht the following input:
"Define the notion of quantifier elimination: A first-order theory T in a language L has quantifier elimination if and only if
  for every L-formula phi there exists a quantifier-free L-formula psi such that T models phi
    if and only if T models psi"
.
-/

import Mathlib



set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open FirstOrder FirstOrder.Language


/-- A first-order theory T in a language L has quantifier elimination if and only if
  for every L-formula phi there exists a quantifier-free L-formula psi such that T models phi
    if and only if T models psi -/
def HasQuantifierElimination (L : Language) (T : L.Theory) : Prop :=
  ∀ {n} (φ : L.BoundedFormula Empty n), ∃ (ψ : L.BoundedFormula Empty n), ψ.IsQF ∧ (φ ⇔[T] ψ)
